<?php 
    define('URL','http://localhost/proyectofinal/code/');
    define('URL_V_ADMIN','http://localhost/proyectofinal/code/views/admin/');
    define('URL_C_ADMIN','http://localhost/proyectofinal/code/controllers/admin/');
    define('URL_M_ADMIN','http://localhost/proyectofinal/code/models/admin/');
    define('HOST','localhost');
    define('DB','hseq');
    define('USERDB','root');
?>